apiVersion: v1
kind: Service
metadata:
  name: ngs-cust
  labels:
    app: ngs-cust
    service: ngs-cust
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: ngs-cust
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ngs-cust
  labels:
    account: ngs-cust